- type: gameMapPool
  id: DefaultMapPool
  maps:
    - ChandlerStation
#  - Aspid
#  - Bagel
#  - Barratry
#  - Box
#  - Cluster
#  - Fland
#  - Kettle
#  - Marathon
#  - Meta
#  - Moose
#  - Omega
#  - Origin

